name: t_store
description: A new Flutter project.
  pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to:

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  http: ^1.1.2
  cupertino_icons: ^1.0.6
  get_storage: ^2.1.1
  get: ^4.6.6
  flutter_local_notifications: ^16.3.0
  intl: ^0.18.0
  logger: ^2.0.2+1
  url_launcher: ^6.2.2

  google_fonts: ^6.1.0
  date_picker_timeline: ^1.2.5
  sqflite: ^2.3.0
  flutter_staggered_animations: ^1.1.1
  flutter_svg: ^2.0.9
  rxdart: ^0.27.7
  provider: ^6.1.1
  flutter_bloc: ^8.1.3
  flutter_smart_dialog: ^4.9.6
  progress_dialog_null_safe: ^1.0.7
  fluttertoast: ^8.2.2
  equatable: ^2.0.0
  flutter_native_splash: ^2.3.9
  smooth_page_indicator: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true
  assets:
    - assets/images/onboarding1.png
    - assets/images/onboarding2.png
    - assets/images/onboarding3.png
    - assets/logos/logo.png
    - assets/icons/google.png
    - assets/icons/facebook.png
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Black.ttf
        - asset: assets/fonts/Roboto-BlackItalic.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto-BoldItalic.ttf
        - asset: assets/fonts/Roboto-Italic.ttf
